name: Deploy Node Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USER }}/mern-node-app  .
      - name: Publish Image to docker hub
        run: docker push ${{ secrets.DOCKER_USER }}/mern-node-app:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull ${{ secrets.DOCKER_USER }}/mern-node-app:latest 
      - name: Delete old container
        run: docker rm -f mern-node-app-container  
      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name mern-node-app-container -e DB_NAME='${{ secrets.DB_NAME }}' -e DB_URI='${{ secrets.DB_URI }}' ${{ secrets.DOCKER_USER }}/mern-node-app